-- ============================================================
-- CompanyModuleAuthority — Bulk Insert (ModuleIDs 1–7)
-- Idempotent: skips rows that already exist
-- ============================================================

INSERT INTO CompanyModuleAuthority (CompanyUserID, ModuleID)
SELECT c.CompanyUserID, m.ModuleID
FROM (VALUES
    ('duttapress'),
    ('kreatica'),
    ('indusvikram'),
    ('shellprintpack'),
    ('GairEnterprises'),
    ('Orientlithopress'),
    ('Orientuniversal'),
    ('durrant'),
    ('surajprintpackweb'),
    ('GraphicSystems'),
    ('rsgraphics'),
    ('Salasar'),
    ('pragatioffset'),
    ('RASHTROTTHANA'),
    ('printmegood'),
    ('pragatilabel'),
    ('NineStepWeb'),
    ('PBTesting'),
    ('scantrans'),
    ('CDC'),
    ('SaiSriLabels'),
    ('Boxpool'),
    ('Packlabs'),
    ('Parthprint'),
    ('sterlinggraphics'),
    ('induswebn'),
    ('MarksPrint'),
    ('Quantum'),
    ('gujaratoffset'),
    ('designindiaweb'),
    ('Nukkad'),
    ('SriKriscon'),
    ('indusritesh'),
    ('digiprint1'),
    ('AMBAMULTIPRINT'),
    ('digiprintweb'),
    ('Orientlithopressbkp'),
    ('RKEnterprises'),
    ('jayantprinteryweb'),
    ('jbvsn'),
    ('RASKIN'),
    ('WeePrint'),
    ('RangoliOffset'),
    ('IndusAmit'),
    ('Skumar'),
    ('Shriroop'),
    ('Nageen'),
    ('InduswebF'),
    ('Arihant'),
    ('Shubham'),
    ('Reva'),
    ('CMYK'),
    ('OrientColorArt'),
    ('AAA'),
    ('ArihantPrinters'),
    ('SFAPRINT'),
    ('Krishnalabels'),
    ('GRAPHICPRINTS'),
    ('ContinuityWeb'),
    ('SSS'),
    ('PBHOLOTECH'),
    ('RajeshOffset'),
    ('indusweb'),
    ('AAAAAAA'),
    ('Rainbow'),
    ('OCEANS'),
    ('thomson'),
    ('SkyPrint'),
    ('DEEPPACKAGING'),
    ('GoodLuck'),
    ('ShethImpressionXL'),
    ('OnlinePrint'),
    ('Anaswara'),
    ('Quarterfoldtesting'),
    ('MPAD'),
    ('PackPlay'),
    ('LOKENATH'),
    ('Designprint'),
    ('VIJAYSHRI'),
    ('Swastik'),
    ('ShreeCalendar'),
    ('AmarUjalaJammu'),
    ('Joseph'),
    ('ArabWeb'),
    ('Abhishek'),
    ('Eastern'),
    ('QuarterfoldWeb'),
    ('Tajpress'),
    ('ShreeGanesh'),
    ('PackOPrint'),
    ('RGPack'),
    ('Omega'),
    ('Sreekrishna'),
    ('SARASWATI'),
    ('DesignPlus'),
    ('Mytec'),
    ('KnitCity'),
    ('Techno'),
    ('Indust'),
    ('OrangePrinters'),
    ('OrientPack'),
    ('multiunittesting'),
    ('Avantika'),
    ('vikasoffset'),
    ('Khosla'),
    ('ArtOPrint'),
    ('Vijay Printing'),
    ('NextgenSikkimWeb'),
    ('Shivganga'),
    ('IndusEnterprisetesting123'),
    ('Novel'),
    ('ThomsonUIUX'),
    ('NextgenKolkataWeb'),
    ('MaxCreative'),
    ('Durgesh'),
    ('AnaswaraBkp'),
    ('UGS'),
    ('SilverLine'),
    ('Pioneer'),
    ('PrinceGraphics'),
    ('Ajooni'),
    ('Winways'),
    ('SilverpointPress'),
    ('SWANPRESS'),
    ('Harshal'),
    ('GoodLuckBkp'),
    ('SarojPrintBkp'),
    ('SriVaishnavi'),
    ('Sarojprint'),
    ('JaipurPrinters'),
    ('SuriGraphixWeb'),
    ('ManaliWeb'),
    ('Eskays'),
    ('LovelyWeb'),
    ('LaxmiPharma'),
    ('2KMLabel'),
    ('GoodLucktest'),
    ('Impression'),
    ('SuriGraphix'),
    ('PreparedOffset'),
    ('VIVIInternational'),
    ('Smith'),
    ('VamsiArt'),
    ('AcmeWeb'),
    ('Label Wala'),
    ('Saroj'),
    ('Testing'),
    ('FinancialTesting'),
    ('NITAIPRESS'),
    ('JayOffset'),
    ('Indas555'),
    ('digiprint'),
    ('HindustanLabels'),
    ('Printwell'),
    ('ShreedharWeb'),
    ('Testcrm'),
    ('CRMTESTING'),
    ('MK'),
    ('KeyLine'),
    ('VRINDAPRINT'),
    ('LIVEART DESIGN'),
    ('PearlPrintweb'),
    ('ArtOPrintFlexo'),
    ('MaharashtraBook'),
    ('Benchmark'),
    ('NextGenunit3'),
    ('ColorPoint1'),
    ('HiraPrintWeb'),
    ('GaneshPaper'),
    ('RightwayPackaging'),
    ('NITAIPRESS1'),
    ('OrangePrintersbkp'),
    ('Incrollers'),
    ('Peramount'),
    ('Sakura'),
    ('Tarun'),
    ('BHAGINI'),
    ('SBM'),
    ('Parksons'),
    ('GitaPress'),
    ('Sweta'),
    ('AshishOffset')
) AS c(CompanyUserID)
CROSS JOIN (VALUES (1),(2),(3),(4),(5),(6),(7)) AS m(ModuleID)
WHERE NOT EXISTS (
    SELECT 1 FROM CompanyModuleAuthority existing
    WHERE existing.CompanyUserID = c.CompanyUserID
      AND existing.ModuleID = m.ModuleID
);

-- Verify: count inserted per company
-- SELECT CompanyUserID, COUNT(*) AS ModuleCount
-- FROM CompanyModuleAuthority
-- WHERE ModuleID IN (1,2,3,4,5,6,7)
-- GROUP BY CompanyUserID
-- ORDER BY CompanyUserID;
